name: Deploy Hugo site to Cloudflare Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deployment.outputs.url }}
    env:
      HUGO_VERSION: 0.125.6
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node modules
        run: |-
          hugo mod npm pack
          npm install

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jobstoit
          directory: ./public
